[build]
  command = "CI=false npm run build"
  publish = "build"
  node_version = "18"

[build.environment]
  NODE_VERSION = "18"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200